# -*- coding: utf-8 -*-
"""
@author: Eric Friesen Waldner, September 23, 2026 
"""
#A single plane plot generator for providing a plane to the interactive plotter to allow the user to put a line over it.

import os
#import glob
import numpy as np
#import sys
import re
from matplotlib import pyplot as plt
#from natsort import natsorted

from postprocessing.bulk_potential_plotter import list_to_array_float, folder_finder, npy_file_sorter, title_maker_line_plot, regex_pattern_for_npys

      
def single_plane_plotter(potentials_to_plot, axis_choice, plane_positions):
    
    #Pull relevant parameters out of a representative filename
    representative_file = os.path.basename(potentials_to_plot[0])  #representative_file will be resused for the plot titling function later
    Lx, Ly, Lz, Nx, Ny, Nz, Bias = regex_pattern_for_npys(representative_file)
    

    print(f"Slices will be plotted along {axis_choice} at {plane_positions} nm") 
    for j in enumerate(potentials_to_plot): #Choose the j-th file in the list of paths provided
        phi_file = np.load(j[1])
        
        file_name = os.path.basename(j[1]) #Gets just the filename for creating the legend title
        #Pulls out the tip height from the bottom of the simulation space using regular expressions
        tip_height_pattern = re.compile(r".*?TipHeightfromBottom_(?P<tip_height>[\d.]+)nm_.*?")
        m = re.match(tip_height_pattern, file_name)
        tip_height = m.groupdict()["tip_height"] #Saves this future label for the plot

        for i in plane_positions: #The list of all desired slice heights in the chosen axis of the simulation space
            #The slice of potential from each file will be plotted, at each height
            fig, ax = plt.subplots() #Create one imshow() plot of the slice at each height:
                
            #The code will now take the position of each slice generated by the user input
            #  and convert them from real values into the corresponding/closest
            #  part of the output potential .npy file matrix,
            #  by dividing the input position by length and multiplying by resolution
            if axis_choice == "xy":
                iz = int((i/Lz)*(Nz))
                phi_slice = phi_file[:,:,iz]
                slice_extent = [0, Lx, 0, Ly]
                slice_title_pos = f'z = {iz:.2f} nm'
                line_xlabel = 'x (nm)'
                line_ylabel = 'y (nm)'
                length = Lz
                density = Nz
                
            if axis_choice == "yz":
                ix = int((i/Lx)*(Nx))
                phi_slice = phi_file[ix,:,:]
                slice_extent = [0, Ly, 0, Lz]
                slice_title_pos = f'x = {ix:.2f} nm'
                line_xlabel = 'y (nm)'
                line_ylabel = 'z (nm)'
                length = Lx
                density = Nx
                
            if axis_choice == "xz":
                iy = int((i/Ly)*(Ny))
                phi_slice = phi_file[:,iy,:]
                slice_extent = [0, Lx, 0, Lz]
                slice_title_pos = f'y = {iy:.2f} nm'
                line_xlabel = 'x (nm)'
                line_ylabel = 'z (nm)'
                length = Ly
                density = Ny
                
            ax.set_xlabel(line_xlabel)
            ax.set_ylabel(line_ylabel)  
            
            #Now generate a default title
            sim_name_or_custom_name = title_maker_line_plot(representative_file, "n") #if/else function, allows user to modify the title
            ax.set_title(f' Potential of {sim_name_or_custom_name} along the {axis_choice} plane' 
                         f' at {slice_title_pos}, with Tip Height: {tip_height} nm, Tip Bias Applied: {Bias} V', wrap=True)
            
             
            
            image = plt.imshow(phi_slice.T, origin='lower', interpolation = "none", extent=slice_extent,
                                  cmap='RdBu_r', aspect='equal') #aspect makes all of the pixels square
            plt.colorbar(image, label='Potential (V)')

            fig = plt.gcf()
            plt.show()  #Commented this out since the interactive plotter does the plotting
    
    return fig, length, density


def bulk_potential_slices():
  
    #Asks the user what folder they would like to look for .npy files in
    npy_directory = folder_finder()
    #Next finds all files ending in .npy and return them sorted alphabetically
    npy_files = npy_file_sorter(npy_directory)
        
    #User selects file to plot
    choice = input("Select file number: ").strip()
    if choice.isdigit():
        nth_file = int(choice)
        if 0 <= nth_file < len(npy_files): #Double check the number entered is valid
            potentials_to_plot = [npy_files[nth_file]]
            print(f"Plotting {potentials_to_plot}")
    else:
        print("Invalid Input. Start Again")
        return bulk_potential_slices()

    #Now we have a single potential file to plot

    #Next the user chooses desired axis of the plane
    def plane_or_line_and_axis_choice():
            
        axis_choice = input("What axis would you like to slice? 'xz', 'yz', or 'xy' (default: xy): ").strip()
        if axis_choice == "xz":
            print("Plotting in xz.")
        elif axis_choice == "yz":
            print("Plotting in yz.")
        elif axis_choice == "xy" or axis_choice == "":
            axis_choice = "Plotting in xy."
            axis_choice = "xy"
        else:
            print("Invalid choice, try again.")
            return plane_or_line_and_axis_choice() #run the function again
        return(axis_choice)  


    #Now call the function defined above to get the desired axis_choice and positions
    axis_choice = plane_or_line_and_axis_choice()
    print(f"Plotting in {axis_choice}")


    print(f"Where along the not chosen axis in the simulation space would you like to plot the plane slice(s) of potential in {axis_choice}? (default: 50 nm)")
    plane_positions = input("Input a list of values in nm (e.g. take a slice in xy for z values (10, 20, 30) nm) (default 50 nm): ").strip()
    plane_positions = list_to_array_float(plane_positions)

            
    #Now runs the plotting function
    fig, length, density  = single_plane_plotter(potentials_to_plot, axis_choice, plane_positions)
         
    return fig, length, density

